// <auto-generated />
namespace BugTracker_2019_09_17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tryingEnumOnStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryingEnumOnStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201909202003263_tryingEnumOnStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
